version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  # 或者选择您的 Java 版本，如 corretto8, corretto17
    commands:
      - echo Installing dependencies...
      - cd health
      - mvn install -DskipTests  # 安装依赖并跳过测试
  pre_build:
    commands:
      - echo Pre-build stage...
      - pwd  # 打印当前工作目录
      - ls -l  # 列出当前目录下的文件和子目录
      - mvn clean
  build:
    commands:
      - echo Build started on `date`
      - pwd  # 打印当前工作目录
      - ls -l  # 列出当前目录下的文件和子目录
      - mvn package  # 构建 Spring Boot 项目
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Build finished

artifacts:
  files:
    - target/*.jar  # 指定打包生成的 jar 文件位置
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'  # Maven 缓存目录
